const DATA = [
  {
    MemberId: 1770,
    createdAt: '2016-10-02 23:30',
    type: 'ORGANIZATION',
    role: 'HOST',
    isActive: true,
    totalAmountDonated: 0.58,
    currency: 'USD',
    lastTransactionAt: '2021-08-22 14:51',
    lastTransactionAmount: -0.2,
    profile: 'https://opencollective.com/opensource',
    name: 'Open Source Collective',
    company: null,
    description:
      'Non-profit fiscal host promoting a healthy and sustainable open source ecosystem.',
    image:
      'https://opencollective-production.s3.us-west-1.amazonaws.com/97017710-a90f-11e9-b6fb-2bbe7128f780.png',
    email: null,
    twitter: 'https://twitter.com/opencollect',
    github: null,
    website: 'https://oscollective.org',
  },
  {
    MemberId: 1911,
    createdAt: '2016-10-17 00:00',
    type: 'ORGANIZATION',
    role: 'BACKER',
    isActive: true,
    totalAmountDonated: 200,
    currency: 'USD',
    lastTransactionAt: '2017-01-13 00:00',
    lastTransactionAmount: 100,
    profile: 'https://opencollective.com/idonethis',
    name: 'I Done This',
    company: null,
    description:
      'More than 160,000 people use I Done This’s easy daily check-ins and powerful progress reports to run more effective and productive teams.',
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/06a44500-1ecc-11e7-be1e-a32c54219e24.png',
    email: null,
    twitter: 'https://twitter.com/idonethis',
    github: null,
    website: null,
  },
  {
    MemberId: 1918,
    createdAt: '2016-10-18 12:18',
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    totalAmountDonated: 1600,
    currency: 'USD',
    lastTransactionAt: '2018-01-18 13:19',
    lastTransactionAmount: 100,
    profile: 'https://opencollective.com/vtex',
    name: 'VTEX',
    company: null,
    description: 'We are creating the first ever commerce app platform!',
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/caeef5f0-b33b-11e7-be98-3b0d70a7d9c4.png',
    email: null,
    twitter: 'https://twitter.com/vtextruecloud',
    github: null,
    website: 'https://engineering.vtex.com',
  },
  {
    MemberId: 1933,
    createdAt: '2016-10-20 12:59',
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    totalAmountDonated: 5800,
    currency: 'USD',
    lastTransactionAt: '2021-08-01 03:10',
    lastTransactionAmount: 100,
    profile: 'https://opencollective.com/peerigon',
    name: 'Peerigon',
    company: null,
    description: 'We love Open Source and the Open Web!',
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/b979b5a0-b1ad-11e8-8269-5bfc5ed73cbb.png',
    email: null,
    twitter: 'https://twitter.com/peerigon',
    github: null,
    website: 'https://peerigon.com/',
  },
  {
    MemberId: 1936,
    createdAt: '2016-10-20 14:57',
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    totalAmountDonated: 3900,
    currency: 'USD',
    lastTransactionAt: '2019-12-21 05:01',
    lastTransactionAmount: 100,
    profile: 'https://opencollective.com/photoeditorsdk',
    name: 'PhotoEditorSDK',
    company: null,
    description: null,
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/801e50f0-418f-11e9-9e72-7df8a879b912.png',
    email: null,
    twitter: 'https://twitter.com/photoeditorsdk',
    github: null,
    website:
      'https://www.photoeditorsdk.com/?utm_source=sponsorship&utm_medium=logo&utm_campaign=webpack_sponsorship',
  },
  {
    MemberId: 1981,
    createdAt: '2016-10-24 07:21',
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    totalAmountDonated: 1500,
    currency: 'USD',
    lastTransactionAt: '2017-12-24 08:22',
    lastTransactionAmount: 100,
    profile: 'https://opencollective.com/x-team',
    name: 'X-Team',
    company: null,
    description:
      'Motivated developers, ready to join your team. http://x-team.com',
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/a9c3b140-99ba-11e6-8650-f92e594d5de8.png',
    email: null,
    twitter: 'https://twitter.com/xteam',
    github: null,
    website: 'https://x-team.com',
  },
  {
    MemberId: 2048,
    createdAt: '2016-10-31 17:40',
    type: 'ORGANIZATION',
    role: 'BACKER',
    isActive: true,
    totalAmountDonated: 300,
    currency: 'USD',
    lastTransactionAt: '2016-10-31 17:40',
    lastTransactionAmount: 300,
    profile: 'https://opencollective.com/workco',
    name: 'Work & Co',
    company: null,
    description: null,
    image: 'https://logo.clearbit.com/work.co',
    email: null,
    twitter: 'https://twitter.com/workandco',
    github: null,
    website: 'https://work.co/',
  },
  {
    MemberId: 2054,
    createdAt: '2016-11-01 12:52',
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Sponsor',
    isActive: false,
    totalAmountDonated: 750,
    currency: 'USD',
    lastTransactionAt: '2017-01-01 13:53',
    lastTransactionAmount: 250,
    profile: 'https://opencollective.com/moduscreate',
    name: 'Modus Create',
    company: null,
    description: null,
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/090a1f80-150c-11e9-819f-d376f18af389.png',
    email: null,
    twitter: 'https://twitter.com/ModusCreate',
    github: 'https://github.com/moduscreate',
    website: 'https://moduscreate.com',
  },
  {
    MemberId: 2160,
    createdAt: '2016-11-11 14:52',
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    totalAmountDonated: 1503,
    currency: 'USD',
    lastTransactionAt: '2019-12-19 09:47',
    lastTransactionAmount: 103,
    profile: 'https://opencollective.com/algolia',
    name: 'Algolia',
    company: null,
    description:
      'A powerful hosted search engine API, Algolia provides product teams with the resources & tools they need to create fast, relevant search.',
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/a3f24d90-7639-11e9-9c33-1b4223aef030.png',
    email: null,
    twitter: 'https://twitter.com/algolia',
    github: 'https://github.com/algolia',
    website: 'https://algolia.com',
  },
  {
    MemberId: 2258,
    createdAt: '2016-11-23 11:42',
    type: 'ORGANIZATION',
    role: 'BACKER',
    isActive: true,
    totalAmountDonated: 4522,
    currency: 'USD',
    lastTransactionAt: '2017-09-23 12:43',
    lastTransactionAmount: 2,
    profile: 'https://opencollective.com/tipe',
    name: 'Tipe',
    company: null,
    description:
      'Tipe is a customizable, open-source headless CMS. We handle the infrastructure and your team gets to edit everything.',
    image:
      'https://opencollective-production.s3-us-west-1.amazonaws.com/58581ee0-e4f5-11e7-9265-3f31ae7252f5.png',
    email: null,
    twitter: 'https://twitter.com/TipeIO',
    github: 'https://github.com/tipeio',
    website: 'https://tipe.io?ref=opencollective',
  },
];

export default DATA;
